/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learner */
        get: operations["getLearner"];
        /** Update Learner */
        put: operations["updateLearner"];
        /** Create Learner */
        post: operations["createLearner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["getSettings"];
        /** Update Settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Exercise */
        post: operations["prepareExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grammar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grammar */
        get: operations["listGrammar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grammar/{grammar_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grammar */
        get: operations["getGrammar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Evaluation */
        post: operations["explainEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grammar/{grammar_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Grammar */
        post: operations["explainGrammar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerError */
        AnswerError: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Original */
            original: string;
            /** Correction */
            correction: string;
            /** Item Id */
            item_id: string | null;
            /** Diagnostic Tags */
            diagnostic_tags: string[];
            /**
             * Severity
             * @enum {string}
             */
            severity: "minor" | "major";
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string;
        };
        /** AnswerIn */
        AnswerIn: {
            /** Exercise Id */
            exercise_id: string;
            answer?: components["schemas"]["AnswerPayload"];
            /**
             * Used Hint
             * @default false
             */
            used_hint: boolean;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** AnswerOut */
        AnswerOut: {
            /**
             * Kind
             * @default flashcard
             * @constant
             */
            kind: "flashcard";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "assisted" | "error";
            expected: components["schemas"]["ExpectedAnswer"] | null;
            /** Diagnostic Tags */
            diagnostic_tags: string[];
            /** Feedback It */
            feedback_it: string;
            memory: components["schemas"]["MemoryOut"] | null;
        };
        /** AnswerPayload */
        AnswerPayload: {
            /** Choice */
            choice?: number | null;
            /** Text */
            text?: string | null;
        };
        /** CardExample */
        CardExample: {
            /** De */
            de: string;
            /** It */
            it: string;
        };
        /**
         * CardPrompt
         * @description Prompt shown to the learner. Fields depend on the card type; unused ones are null.
         */
        CardPrompt: {
            /** De */
            de?: string | null;
            /** It */
            it?: string | null;
            /** Pos */
            pos?: string | null;
            /** Options */
            options?: string[] | null;
            /** Needs Article */
            needs_article?: boolean | null;
            /** Lemma */
            lemma?: string | null;
            /** Article */
            article?: string | null;
            /** Plural */
            plural?: string | null;
            /** Translation It */
            translation_it?: string | null;
            /** Translation En */
            translation_en?: string | null;
            example?: components["schemas"]["CardExample"] | null;
            /** Interference Note */
            interference_note?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
            /** Reference It */
            reference_it?: string | null;
            /** Examples */
            examples?: components["schemas"]["CardExample"][] | null;
        };
        /** EvaluationExplainIn */
        EvaluationExplainIn: {
            /** Item Id */
            item_id: string;
        };
        /** ExpectedAnswer */
        ExpectedAnswer: {
            /** Text */
            text: string;
            /** Lemma */
            lemma: string;
            /** Article */
            article?: string | null;
            /** Plural */
            plural?: string | null;
            /** Translation It */
            translation_it: string;
            example?: components["schemas"]["CardExample"] | null;
            /** Correct Index */
            correct_index?: number | null;
        };
        /** ExplanationExampleOut */
        ExplanationExampleOut: {
            /** De */
            de: string;
            /** Translation */
            translation: string;
        };
        /** ExplanationOut */
        ExplanationOut: {
            /** Markdown */
            markdown: string;
            /** Examples */
            examples: components["schemas"]["ExplanationExampleOut"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** GlossaryEntry */
        GlossaryEntry: {
            /** Item Id */
            item_id: string;
            /** De */
            de: string;
            /** Translation */
            translation: string;
        };
        /** GrammarDetail */
        GrammarDetail: {
            /** Id */
            id: string;
            /** Title It */
            title_it: string;
            /** Title En */
            title_en: string;
            /** Level */
            level: string;
            /** Requires */
            requires: string[];
            /** Diagnostic Tags */
            diagnostic_tags: {
                [key: string]: string[];
            };
            /** Reference It */
            reference_it: string;
            /** Examples */
            examples: components["schemas"]["GrammarExample"][];
        };
        /** GrammarExample */
        GrammarExample: {
            /** De */
            de: string;
            /** It */
            it: string;
        };
        /** GrammarExplainIn */
        GrammarExplainIn: {
            /** Question */
            question: string;
        };
        /** GrammarSummary */
        GrammarSummary: {
            /** Id */
            id: string;
            /** Title It */
            title_it: string;
            /** Level */
            level: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
            /**
             * Llm
             * @enum {string}
             */
            llm: "fake" | "anthropic";
        };
        /** ItemDetail */
        ItemDetail: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lemma" | "grammar" | "construction";
            /** Level */
            level: string;
            /** Label */
            label: string;
            /** Translation It */
            translation_it: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Interference */
            interference: {
                [key: string]: unknown;
            };
            /** Requires */
            requires: string[];
            /** Frequency Zipf */
            frequency_zipf: number | null;
            /** Suspended */
            suspended: boolean;
            /** Status */
            status: ("unseen" | "presumed_known" | "candidate" | "introduced" | "suspended") | null;
            /** Candidate Source */
            candidate_source: string | null;
            /** Introduced At */
            introduced_at: string | null;
            /** Memory */
            memory: components["schemas"]["MemoryEntry"][];
        };
        /** ItemList */
        ItemList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["ItemSummary"][];
        };
        /** ItemResult */
        ItemResult: {
            /** Item Id */
            item_id: string;
            /** Label */
            label: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "assisted" | "error";
            /** Needs Remediation */
            needs_remediation: boolean;
        };
        /** ItemSummary */
        ItemSummary: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lemma" | "grammar" | "construction";
            /** Level */
            level: string;
            /** Label */
            label: string;
            /** Translation It */
            translation_it: string | null;
            /** Status */
            status: ("unseen" | "presumed_known" | "candidate" | "introduced" | "suspended") | null;
            /** Memory */
            memory: components["schemas"]["MemoryEntry"][];
        };
        /** LearnerCreate */
        LearnerCreate: {
            /**
             * Level
             * @enum {string}
             */
            level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** Known Languages */
            known_languages?: string[];
            /**
             * Explanation Language
             * @default it
             */
            explanation_language: string;
        };
        /** LearnerOut */
        LearnerOut: {
            /** Id */
            id: number;
            /**
             * Level
             * @enum {string}
             */
            level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** Known Languages */
            known_languages: string[];
            /** Explanation Language */
            explanation_language: string;
            settings: components["schemas"]["SettingsOut"];
        };
        /** LearnerUpdate */
        LearnerUpdate: {
            /** Level */
            level?: ("A1" | "A2" | "B1" | "B2" | "C1" | "C2") | null;
            /** Known Languages */
            known_languages?: string[] | null;
            /** Explanation Language */
            explanation_language?: string | null;
        };
        /** MemoryEntry */
        MemoryEntry: {
            /** Facet */
            facet: string;
            /** Due */
            due: string | null;
            /** Mastery */
            mastery: number;
            /** Stability */
            stability: number | null;
        };
        /** MemoryOut */
        MemoryOut: {
            /** Facet */
            facet: string;
            /** Due */
            due: string | null;
            /** Mastery */
            mastery: number;
        };
        /**
         * PreparedCard
         * @description Result of `prepare`; `fallback_cards` are flashcard intros when generation failed.
         */
        PreparedCard: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flashcard_intro" | "flashcard_recognition" | "flashcard_production" | "grammar_intro" | "production";
            /** Item Id */
            item_id?: string | null;
            prompt?: components["schemas"]["CardPrompt"];
            /** Hint */
            hint?: string | null;
            /**
             * Status
             * @default ready
             * @enum {string}
             */
            status: "pending" | "ready" | "answered" | "failed";
            /** Subtype */
            subtype?: ("translation" | "guided" | "transform") | null;
            /** Instructions */
            instructions?: string | null;
            /** Glossary */
            glossary?: components["schemas"]["GlossaryEntry"][];
            /** Item Ids */
            item_ids?: string[];
            /** Fallback Cards */
            fallback_cards?: components["schemas"]["SessionCard"][];
        };
        /** ProductionAnswerOut */
        ProductionAnswerOut: {
            /**
             * Kind
             * @default production
             * @constant
             */
            kind: "production";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "minor_errors" | "major_errors" | "off_task";
            /** Corrected Sentence */
            corrected_sentence: string;
            /** Errors */
            errors: components["schemas"]["AnswerError"][];
            /** Feedback */
            feedback: string;
            /** Items */
            items: components["schemas"]["ItemResult"][];
            /** Evaluation Id */
            evaluation_id: number;
        };
        /**
         * SessionCard
         * @description A card of the session.
         *
         *     Every card carries a `CardPrompt` in `prompt`. Production exercises put the generated text in
         *     `prompt.text` (null until `prepare` has run) and also set `subtype`, `instructions`,
         *     `glossary` and `item_ids`; `item_id` is their primary target.
         */
        SessionCard: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flashcard_intro" | "flashcard_recognition" | "flashcard_production" | "grammar_intro" | "production";
            /** Item Id */
            item_id?: string | null;
            prompt?: components["schemas"]["CardPrompt"];
            /** Hint */
            hint?: string | null;
            /**
             * Status
             * @default ready
             * @enum {string}
             */
            status: "pending" | "ready" | "answered" | "failed";
            /** Subtype */
            subtype?: ("translation" | "guided" | "transform") | null;
            /** Instructions */
            instructions?: string | null;
            /** Glossary */
            glossary?: components["schemas"]["GlossaryEntry"][];
            /** Item Ids */
            item_ids?: string[];
        };
        /** SessionOut */
        SessionOut: {
            /** Session Id */
            session_id: string;
            /** Cards */
            cards: components["schemas"]["SessionCard"][];
        };
        /** SettingsOut */
        SettingsOut: {
            /** Weekly New Lemmas */
            weekly_new_lemmas: number;
            /** Weekly New Grammar */
            weekly_new_grammar: number;
            /** Desired Retention */
            desired_retention: number;
            /** Review Cap */
            review_cap: number;
            /** New Per Session */
            new_per_session: number;
            /** Production Slots */
            production_slots: number;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Weekly New Lemmas */
            weekly_new_lemmas?: number | null;
            /** Weekly New Grammar */
            weekly_new_grammar?: number | null;
            /** Desired Retention */
            desired_retention?: number | null;
            /** Review Cap */
            review_cap?: number | null;
            /** New Per Session */
            new_per_session?: number | null;
            /** Production Slots */
            production_slots?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerOut"];
                };
            };
        };
    };
    updateLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    prepareExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"] | components["schemas"]["ProductionAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: {
                kind?: ("lemma" | "grammar" | "construction") | null;
                level?: string | null;
                status?: ("unseen" | "presumed_known" | "candidate" | "introduced" | "suspended") | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listGrammar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrammarSummary"][];
                };
            };
        };
    };
    getGrammar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grammar_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrammarDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explainEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explainGrammar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grammar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrammarExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
