/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learner */
        get: operations["getLearner"];
        /** Update Learner */
        put: operations["updateLearner"];
        /** Create Learner */
        post: operations["createLearner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["getSettings"];
        /** Update Settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Exercise */
        post: operations["prepareExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["listItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grammar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grammar */
        get: operations["listGrammar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grammar/{grammar_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grammar */
        get: operations["getGrammar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Evaluation */
        post: operations["explainEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grammar/{grammar_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Grammar */
        post: operations["explainGrammar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/texts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Texts */
        get: operations["listTexts"];
        put?: never;
        /** Create Text */
        post: operations["createText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/texts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Text */
        post: operations["generateText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/texts/{text_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Text */
        get: operations["getText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/texts/{text_id}/reading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Reading */
        post: operations["startReading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{reading_id}/gloss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gloss Token */
        post: operations["glossToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{reading_id}/optin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optin Token */
        post: operations["optinToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reading/{reading_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Reading */
        post: operations["finishReading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Queue */
        get: operations["getQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/optin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optin Item */
        post: operations["optinItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/optout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optout Item */
        post: operations["optoutItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/contest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Contest Evaluation */
        post: operations["contestEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/contest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Contest Attempt
         * @description Contest an attempt; flashcard attempts from before M4 get their evaluation on demand.
         */
        post: operations["contestAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contests */
        get: operations["listContests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Placement */
        post: operations["startPlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/placement/{placement_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish Placement */
        post: operations["finishPlacement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerError */
        AnswerError: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Original */
            original: string;
            /** Correction */
            correction: string;
            /** Item Id */
            item_id: string | null;
            /** Diagnostic Tags */
            diagnostic_tags: string[];
            /**
             * Severity
             * @enum {string}
             */
            severity: "minor" | "major";
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string;
        };
        /** AnswerIn */
        AnswerIn: {
            /** Exercise Id */
            exercise_id: string;
            answer?: components["schemas"]["AnswerPayload"];
            /**
             * Used Hint
             * @default false
             */
            used_hint: boolean;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** AnswerOut */
        AnswerOut: {
            /**
             * Kind
             * @default flashcard
             * @constant
             */
            kind: "flashcard";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "assisted" | "error";
            expected: components["schemas"]["ExpectedAnswer"] | null;
            /** Diagnostic Tags */
            diagnostic_tags: string[];
            /** Feedback It */
            feedback_it: string;
            memory: components["schemas"]["MemoryOut"] | null;
            /** Evaluation Id */
            evaluation_id?: number | null;
            /** Attempt Id */
            attempt_id?: number | null;
        };
        /** AnswerPayload */
        AnswerPayload: {
            /** Choice */
            choice?: number | null;
            /** Text */
            text?: string | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /**
             * Auth
             * @enum {string}
             */
            auth: "enabled" | "disabled";
            /** Authenticated */
            authenticated: boolean;
        };
        /** BandResult */
        BandResult: {
            /** N */
            n: number;
            /** Score */
            score: number;
        };
        /** BudgetOut */
        BudgetOut: {
            /** Lemmas Left */
            lemmas_left: number;
            /** Grammar Left */
            grammar_left: number;
            /** Backlog */
            backlog: number;
        };
        /** CalibrationBucketOut */
        CalibrationBucketOut: {
            /** Bucket Low */
            bucket_low: number;
            /** Bucket High */
            bucket_high: number;
            /** N */
            n: number;
            /** Predicted */
            predicted: number;
            /** Observed */
            observed: number;
            /** Recalled */
            recalled: number;
            /** Assisted */
            assisted: number;
            /** Forgotten */
            forgotten: number;
        };
        /** CardExample */
        CardExample: {
            /** De */
            de: string;
            /** It */
            it: string;
        };
        /**
         * CardPrompt
         * @description Prompt shown to the learner. Fields depend on the card type; unused ones are null.
         */
        CardPrompt: {
            /** De */
            de?: string | null;
            /** It */
            it?: string | null;
            /** Pos */
            pos?: string | null;
            /** Options */
            options?: string[] | null;
            /** Needs Article */
            needs_article?: boolean | null;
            /** Lemma */
            lemma?: string | null;
            /** Article */
            article?: string | null;
            /** Plural */
            plural?: string | null;
            /** Translation It */
            translation_it?: string | null;
            /** Translation En */
            translation_en?: string | null;
            example?: components["schemas"]["CardExample"] | null;
            /** Interference Note */
            interference_note?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
            /** Reference It */
            reference_it?: string | null;
            /** Examples */
            examples?: components["schemas"]["CardExample"][] | null;
        };
        /** ContestIn */
        ContestIn: {
            /** Item Ids */
            item_ids?: string[];
            /** Reason */
            reason?: string | null;
        };
        /** ContestItemOutcome */
        ContestItemOutcome: {
            /** Item Id */
            item_id: string;
            /** Label */
            label: string;
            /** Previous */
            previous: ("correct" | "assisted" | "error") | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "assisted" | "error";
        };
        /** ContestOut */
        ContestOut: {
            /** Id */
            id: number;
            /** Evaluation Id */
            evaluation_id: number;
            /** Item Ids */
            item_ids: string[];
            /** Reason */
            reason: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved";
            /** Verdict */
            verdict: ("accepted" | "rejected" | "partial") | null;
            /** Resolver */
            resolver: string;
            /** Rationale */
            rationale: string;
            /** Replacement Evaluation Id */
            replacement_evaluation_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** ContestResultOut */
        ContestResultOut: {
            contest: components["schemas"]["ContestOut"];
            /** Evaluation Id */
            evaluation_id: number;
            /** Items */
            items: components["schemas"]["ContestItemOutcome"][];
        };
        /** CreateTextIn */
        CreateTextIn: {
            /** Url */
            url?: string | null;
            /** Text */
            text?: string | null;
            /** Title */
            title?: string | null;
        };
        /** EvaluationExplainIn */
        EvaluationExplainIn: {
            /** Item Id */
            item_id: string;
        };
        /** ExpectedAnswer */
        ExpectedAnswer: {
            /** Text */
            text: string;
            /** Lemma */
            lemma: string;
            /** Article */
            article?: string | null;
            /** Plural */
            plural?: string | null;
            /** Translation It */
            translation_it: string;
            example?: components["schemas"]["CardExample"] | null;
            /** Correct Index */
            correct_index?: number | null;
        };
        /** ExplanationExampleOut */
        ExplanationExampleOut: {
            /** De */
            de: string;
            /** Translation */
            translation: string;
        };
        /** ExplanationOut */
        ExplanationOut: {
            /** Markdown */
            markdown: string;
            /** Examples */
            examples: components["schemas"]["ExplanationExampleOut"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** FinishOut */
        FinishOut: {
            /** Session Id */
            session_id: string;
            exercise: components["schemas"]["SessionCard"];
            /** Implicit Events */
            implicit_events: number;
            /** Candidates */
            candidates: string[];
        };
        /** GenerateTextIn */
        GenerateTextIn: {
            /** Topic */
            topic?: string | null;
        };
        /** GlossIn */
        GlossIn: {
            /** Token Index */
            token_index: number;
        };
        /** GlossOut */
        GlossOut: {
            /** Translation */
            translation: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string | null;
            /** Gender */
            gender: string | null;
            /** Plural */
            plural: string | null;
            /** Note */
            note: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "lexicon" | "llm";
            /** Item Id */
            item_id: string | null;
            /**
             * Word Class
             * @enum {string}
             */
            word_class: "ignore" | "known" | "presumed_known" | "auto_candidate" | "optin" | "optin_unlisted" | "ignore_compound";
            /** Can Optin */
            can_optin: boolean;
        };
        /** GlossaryEntry */
        GlossaryEntry: {
            /** Item Id */
            item_id: string;
            /** De */
            de: string;
            /** Translation */
            translation: string;
        };
        /** GrammarDetail */
        GrammarDetail: {
            /** Id */
            id: string;
            /** Title It */
            title_it: string;
            /** Title En */
            title_en: string;
            /** Level */
            level: string;
            /** Requires */
            requires: string[];
            /** Diagnostic Tags */
            diagnostic_tags: {
                [key: string]: string[];
            };
            /** Reference It */
            reference_it: string;
            /** Examples */
            examples: components["schemas"]["GrammarExample"][];
        };
        /** GrammarExample */
        GrammarExample: {
            /** De */
            de: string;
            /** It */
            it: string;
        };
        /** GrammarExplainIn */
        GrammarExplainIn: {
            /** Question */
            question: string;
        };
        /** GrammarSummary */
        GrammarSummary: {
            /** Id */
            id: string;
            /** Title It */
            title_it: string;
            /** Level */
            level: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
            /**
             * Llm
             * @enum {string}
             */
            llm: "fake" | "anthropic";
            /**
             * Auth
             * @enum {string}
             */
            auth: "enabled" | "disabled";
        };
        /** ItemDetail */
        ItemDetail: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lemma" | "grammar" | "construction";
            /** Level */
            level: string;
            /** Label */
            label: string;
            /** Translation It */
            translation_it: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Interference */
            interference: {
                [key: string]: unknown;
            };
            /** Requires */
            requires: string[];
            /** Frequency Zipf */
            frequency_zipf: number | null;
            /** Suspended */
            suspended: boolean;
            /** Status */
            status: ("unseen" | "presumed_known" | "candidate" | "introduced" | "suspended") | null;
            /** Candidate Source */
            candidate_source: string | null;
            /** Introduced At */
            introduced_at: string | null;
            /** Memory */
            memory: components["schemas"]["MemoryEntry"][];
        };
        /** ItemList */
        ItemList: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["ItemSummary"][];
        };
        /** ItemResult */
        ItemResult: {
            /** Item Id */
            item_id: string;
            /** Label */
            label: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "assisted" | "error";
            /** Needs Remediation */
            needs_remediation: boolean;
        };
        /** ItemSummary */
        ItemSummary: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lemma" | "grammar" | "construction";
            /** Level */
            level: string;
            /** Label */
            label: string;
            /** Translation It */
            translation_it: string | null;
            /** Status */
            status: ("unseen" | "presumed_known" | "candidate" | "introduced" | "suspended") | null;
            /** Memory */
            memory: components["schemas"]["MemoryEntry"][];
        };
        /** LearnerCreate */
        LearnerCreate: {
            /**
             * Level
             * @enum {string}
             */
            level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** Known Languages */
            known_languages?: string[];
            /**
             * Explanation Language
             * @default it
             */
            explanation_language: string;
        };
        /** LearnerOut */
        LearnerOut: {
            /** Id */
            id: number;
            /**
             * Level
             * @enum {string}
             */
            level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** Known Languages */
            known_languages: string[];
            /** Explanation Language */
            explanation_language: string;
            settings: components["schemas"]["SettingsOut"];
        };
        /** LearnerUpdate */
        LearnerUpdate: {
            /** Level */
            level?: ("A1" | "A2" | "B1" | "B2" | "C1" | "C2") | null;
            /** Known Languages */
            known_languages?: string[] | null;
            /** Explanation Language */
            explanation_language?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Token */
            token: string;
        };
        /** MemoryEntry */
        MemoryEntry: {
            /** Facet */
            facet: string;
            /** Due */
            due: string | null;
            /** Mastery */
            mastery: number;
            /** Stability */
            stability: number | null;
        };
        /** MemoryOut */
        MemoryOut: {
            /** Facet */
            facet: string;
            /** Due */
            due: string | null;
            /** Mastery */
            mastery: number;
        };
        /** NewWordOut */
        NewWordOut: {
            /** Lemma */
            lemma: string;
            /** Translation */
            translation: string;
        };
        /** OptStatusOut */
        OptStatusOut: {
            /** Item Id */
            item_id: string;
            /** Status */
            status: string;
            /** Candidate Source */
            candidate_source: string | null;
        };
        /** OptinOut */
        OptinOut: {
            /** Item Id */
            item_id: string;
            /** Label */
            label: string;
            /** Status */
            status: string;
            /** Created */
            created: boolean;
        };
        /** PlacementFinishOut */
        PlacementFinishOut: {
            /** Placement Id */
            placement_id: string;
            /** Estimated Level */
            estimated_level: string;
            /** Previous Level */
            previous_level: string;
            /** Changed */
            changed: boolean;
            /** Answered */
            answered: number;
            /** Bands */
            bands: {
                [key: string]: components["schemas"]["BandResult"];
            };
        };
        /** PlacementOut */
        PlacementOut: {
            /** Placement Id */
            placement_id: string;
            /** Cards */
            cards: components["schemas"]["SessionCard"][];
        };
        /**
         * PreparedCard
         * @description Result of `prepare`; `fallback_cards` are flashcard intros when generation failed.
         */
        PreparedCard: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flashcard_intro" | "flashcard_recognition" | "flashcard_production" | "grammar_intro" | "production";
            /** Item Id */
            item_id?: string | null;
            prompt?: components["schemas"]["CardPrompt"];
            /** Hint */
            hint?: string | null;
            /**
             * Status
             * @default ready
             * @enum {string}
             */
            status: "pending" | "ready" | "answered" | "failed";
            /** Subtype */
            subtype?: ("translation" | "guided" | "transform" | "summary") | null;
            /** Instructions */
            instructions?: string | null;
            /** Glossary */
            glossary?: components["schemas"]["GlossaryEntry"][];
            /** Item Ids */
            item_ids?: string[];
            /** Fallback Cards */
            fallback_cards?: components["schemas"]["SessionCard"][];
        };
        /** ProductionAnswerOut */
        ProductionAnswerOut: {
            /**
             * Kind
             * @default production
             * @constant
             */
            kind: "production";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "correct" | "minor_errors" | "major_errors" | "off_task";
            /** Corrected Sentence */
            corrected_sentence: string;
            /** Errors */
            errors: components["schemas"]["AnswerError"][];
            /** Feedback */
            feedback: string;
            /** Items */
            items: components["schemas"]["ItemResult"][];
            /** Evaluation Id */
            evaluation_id: number;
            /** Attempt Id */
            attempt_id?: number | null;
        };
        /** QueueEntry */
        QueueEntry: {
            /** Item Id */
            item_id: string;
            /** Label */
            label: string;
            /**
             * Source
             * @enum {string}
             */
            source: "optin" | "article" | "wordlist";
            /**
             * Kind
             * @enum {string}
             */
            kind: "lemma" | "grammar" | "construction";
        };
        /** QueueOut */
        QueueOut: {
            budget: components["schemas"]["BudgetOut"];
            /** Next */
            next: components["schemas"]["QueueEntry"][];
        };
        /** ReadingOut */
        ReadingOut: {
            /** Id */
            id: number;
            /** Text Version Id */
            text_version_id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * SessionCard
         * @description A card of the session.
         *
         *     Every card carries a `CardPrompt` in `prompt`. Production exercises put the generated text in
         *     `prompt.text` (null until `prepare` has run) and also set `subtype`, `instructions`,
         *     `glossary` and `item_ids`; `item_id` is their primary target.
         */
        SessionCard: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "flashcard_intro" | "flashcard_recognition" | "flashcard_production" | "grammar_intro" | "production";
            /** Item Id */
            item_id?: string | null;
            prompt?: components["schemas"]["CardPrompt"];
            /** Hint */
            hint?: string | null;
            /**
             * Status
             * @default ready
             * @enum {string}
             */
            status: "pending" | "ready" | "answered" | "failed";
            /** Subtype */
            subtype?: ("translation" | "guided" | "transform" | "summary") | null;
            /** Instructions */
            instructions?: string | null;
            /** Glossary */
            glossary?: components["schemas"]["GlossaryEntry"][];
            /** Item Ids */
            item_ids?: string[];
        };
        /** SessionOut */
        SessionOut: {
            /** Session Id */
            session_id: string;
            /** Cards */
            cards: components["schemas"]["SessionCard"][];
        };
        /** SettingsOut */
        SettingsOut: {
            /** Weekly New Lemmas */
            weekly_new_lemmas: number;
            /** Weekly New Grammar */
            weekly_new_grammar: number;
            /** Desired Retention */
            desired_retention: number;
            /** Review Cap */
            review_cap: number;
            /** New Per Session */
            new_per_session: number;
            /** Production Slots */
            production_slots: number;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Weekly New Lemmas */
            weekly_new_lemmas?: number | null;
            /** Weekly New Grammar */
            weekly_new_grammar?: number | null;
            /** Desired Retention */
            desired_retention?: number | null;
            /** Review Cap */
            review_cap?: number | null;
            /** New Per Session */
            new_per_session?: number | null;
            /** Production Slots */
            production_slots?: number | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Reviews 7D */
            reviews_7d: number;
            /** Reviews 30D */
            reviews_30d: number;
            /** Sessions 7D */
            sessions_7d: number;
            /** Readings 7D */
            readings_7d: number;
            /** New Items 7D */
            new_items_7d: number;
            /** Observed Retention */
            observed_retention: number | null;
            /** Target Retention */
            target_retention: number;
            /** Calibration */
            calibration: components["schemas"]["CalibrationBucketOut"][];
            /** Backlog */
            backlog: number;
        };
        /** TextOut */
        TextOut: {
            /** Id */
            id: number;
            /** Source Title */
            source_title: string;
            /** Source Url */
            source_url: string | null;
            /** Source Language */
            source_language: string;
            /** Original */
            original: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            version: components["schemas"]["VersionOut"];
        };
        /** TextSummary */
        TextSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Source Title */
            source_title: string;
            /** Source Url */
            source_url: string | null;
            /** Level */
            level: string;
            /** Coverage */
            coverage: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reading Count */
            reading_count: number;
        };
        /** TokenOut */
        TokenOut: {
            /** I */
            i: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Lemma */
            lemma: string;
            /** Is Alpha */
            is_alpha: boolean;
            /**
             * Word Class
             * @enum {string}
             */
            word_class: "ignore" | "known" | "presumed_known" | "auto_candidate" | "optin" | "optin_unlisted" | "ignore_compound";
            /** Item Id */
            item_id: string | null;
            /** Parts */
            parts: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionOut */
        VersionOut: {
            /** Id */
            id: number;
            /** Level */
            level: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Coverage */
            coverage: number;
            /** Attempt */
            attempt: number;
            /** Tokens */
            tokens: components["schemas"]["TokenOut"][];
            /** New Words */
            new_words: components["schemas"]["NewWordOut"][];
            /** Notes */
            notes: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    getLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerOut"];
                };
            };
        };
    };
    updateLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createLearner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    prepareExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"] | components["schemas"]["ProductionAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: {
                kind?: ("lemma" | "grammar" | "construction") | null;
                level?: string | null;
                status?: ("unseen" | "presumed_known" | "candidate" | "introduced" | "suspended") | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listGrammar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrammarSummary"][];
                };
            };
        };
    };
    getGrammar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grammar_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrammarDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explainEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explainGrammar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grammar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrammarExplainIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTexts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextSummary"][];
                };
            };
        };
    };
    createText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generateText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                text_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                text_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    glossToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optinToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlossIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finishReading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reading_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueOut"];
                };
            };
        };
    };
    optinItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optoutItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contestEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contestAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listContests: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementOut"];
                };
            };
        };
    };
    finishPlacement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlacementFinishOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
}
